name: Secrets

on: [push]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: actions/checkout@v3        
        with:
          token: ${{ secrets.AWS_ACCESS_KEY_ID }}
      - run: echo ${{ secrets.AWS_ACCESS_KEY_ID }}
